### ISSUE TITLE
support backup/restore

### ISSUE THREAD

**Issue by walterra** [walterra/eddoapp#13]
# CouchDB Backup & Restore Implementation Plan

## Overview
This GTD-inspired todo and time tracking application uses PouchDB for offline-first storage. We need robust backup and restore capabilities to protect user data while maintaining the offline-first architecture.

### Recommended Approach: Multi-Strategy Backup
Based on current CouchDB best practices, we should implement multiple backup strategies:

1. **Replication-Based Backup** (Primary)
   - Set up bidirectional replication between multiple CouchDB instances
   - Architecture: `PouchDB <-> Primary CouchDB <-> Backup CouchDB <-> Cloud Storage`
   - Provides both on-site and off-site backups
   - Leverages CouchDB's multi-master architecture

2. **Logical Backup** (Secondary)
   - Use `@cloudant/couchbackup` for JSON-based backups
   - Store backups as compressed files for archival
   - Suitable for point-in-time recovery

#### Primary: @cloudant/couchbackup
- **Most actively maintained** CouchDB backup tool (2025)
- Supports Node.js LTS 20, 22
- Works with CouchDB 2.0+ and Cloudant
- Install: `npm install @cloudant/couchbackup`

#### Alternative: couchdb-backup-restore  
- Creates tar.gz backup files
- Simple Node.js API for programmatic backups
- Install: `npm install couchdb-backup-restore`

### Phase 1: Basic Backup Scripts
Add pnpm scripts for manual backup/restore operations:

```json
{
  "scripts": {
    "backup": "node scripts/backup.js",
    "backup:auto": "node scripts/backup-auto.js",
    "restore": "node scripts/restore.js",
    "backup:verify": "node scripts/verify-backup.js"
  }
}
```

### Phase 2: Automated Backup System
- Daily automated backups via cron/scheduler
- Retention policy (keep daily for 30 days, weekly for 12 weeks, monthly for 12 months)
- Health checks and backup verification
- Cloud storage integration (optional)

### Phase 3: Recovery Tools
- Database restoration from backups
- Conflict resolution for data sync after restore
- Migration tools for backup format changes

### Data Model Compatibility
- Current: TodoAlpha3 with versioned migrations
- Backups must preserve document structure and version info
- Test restore process with each schema migration

### Offline-First Implications
- PouchDB will automatically sync newer data back to restored CouchDB
- No single source of truth - all nodes can accept writes
- Conflict resolution handled by CouchDB's deterministic algorithm

### Limitations to Address
1. **Attachments**: Most tools don't support attachments (not applicable to our current data model)
2. **Revisions**: Backups only preserve current revision (acceptable for our use case)
3. **Multi-node**: Ensure backup covers all shards in CouchDB 2.0+ clusters

## Security & Compliance
- Encrypt backups at rest
- Secure transport for off-site backups
- Access control for backup operations
- Audit trail for backup/restore activities

## Success Criteria
- [ ] Zero data loss during backup/restore cycle
- [ ] Recovery time objective (RTO) < 4 hours
- [ ] Recovery point objective (RPO) < 24 hours
- [ ] Automated daily backups with verification
- [ ] Documented disaster recovery procedures

## Dependencies
- Add `@cloudant/couchbackup` to devDependencies
- Create backup storage location (local + cloud)
- Set up monitoring for backup health

## Related Architecture
This integrates with our existing offline-first architecture:
- React/TypeScript frontend with PouchDB
- MCP server for external integrations  
- Versioned data model with automatic migrations
- Calendar week view with date-range queries

The backup system will preserve all GTD contexts, time tracking data, and calendar-based organization while ensuring data durability.

**Comment by walterra** [comment]
## Final Implementation Status (December 2025)

### ✅ All Success Criteria Met

| Criteria | Status | Details |
|----------|--------|---------|
| Zero data loss during backup/restore cycle | ✅ | Verified via E2E tests |
| Recovery point objective (RPO) < 24 hours | ✅ | Automated daily backups via scheduler |
| Recovery time objective (RTO) < 4 hours | ✅ | Measured and documented (< 1 hour typical) |
| Automated daily backups with verification | ✅ | `pnpm backup:auto` with built-in verification |
| Documented disaster recovery procedures | ✅ | `docs/07_disaster-recovery.md` |

### 📚 Documentation Added

- **Disaster Recovery Guide** (`docs/07_disaster-recovery.md`):
  - Backup strategy overview
  - Step-by-step restore procedures (single DB, full system, point-in-time)
  - RTO benchmarks by database size
  - Environment variable reference
  - Troubleshooting guide
  - Recommended backup schedules

- **README.md** updated with backup section and link to disaster recovery docs

### ⏳ Deferred Items (tracked separately)

**Phase 3 Recovery Tools:**
- Conflict resolution for data sync after restore
- Migration tools for backup format changes

**Security & Compliance:**
- Encrypt backups at rest
- Secure transport for off-site backups
- Access control for backup operations
- Audit trail for backup/restore activities

---

This issue can now be closed. The deferred items are documented in `spec/todo.md` for future consideration.

**Comment by walterra** [comment]
**Correction to previous comment:**

The RTO success criteria should read:

| Criteria | Status | Details |
|----------|--------|---------|
| Recovery time objective (RTO) < 4 hours | ⏳ | Not formally measured - documented factors that affect RTO |

The disaster recovery documentation includes guidance on measuring RTO for production environments, but actual benchmarks were not performed.
